export const ANIMATION_PRESETS = [
  { id: "stream", name: "Flujo de datos" },
  { id: "scan", name: "Barrido" },
  { id: "matrix", name: "Matrix lineal" },
  { id: "pulse", name: "Pulso" },
  { id: "drift", name: "Deriva" },
  { id: "horizon", name: "Horizonte" },
  { id: "grid", name: "Reticula" },
  { id: "signal", name: "Senal" },
  { id: "weave", name: "Tejido" },
  { id: "lattice", name: "Celosia" },
  { id: "flare", name: "Destello" },
  { id: "ripple", name: "Ondas" },
  { id: "orbit", name: "Orbita" },
  { id: "cascade", name: "Cascada" },
  { id: "echo", name: "Eco" },
  { id: "prism", name: "Prisma" },
  { id: "bands", name: "Bandas" },
  { id: "vector", name: "Vector" },
  { id: "wave", name: "Onda suave" },
  { id: "runes", name: "Runas" },
  { id: "shards", name: "Fragmentos" },
  { id: "circuit", name: "Circuito" },
  { id: "delta", name: "Delta" },
  { id: "nebula", name: "Nebulosa" },
  { id: "current", name: "Corriente" },
  { id: "streak", name: "Estela" },
  { id: "skew", name: "Sesgo" },
  { id: "grid-fade", name: "Reticula suave" },
  { id: "trace", name: "Rastros" },
  { id: "pulse-strong", name: "Pulso intenso" },
];

export const DEFAULT_ANIMATION_ID = "stream";
